version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    networks:
      - demoNetwork
  
  mongodb:
    image: mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
    volumes:
      - ./data:/data/db
    networks:
      - demoNetwork

networks:
  demoNetwork:
